[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""

body = """
{%- macro remote_url() -%}
  https://github.com/julienandreu/switchboard
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
            {% if commit.remote.pr_number %} \
                ([#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}))\
            {% endif %}\
    {% endfor %}
{% endfor %}
"""

footer = """
{%- macro remote_url() -%}
  https://github.com/julienandreu/switchboard
{%- endmacro -%}

{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                {{ self::remote_url() }}/compare/{{ release.previous.version }}...{{ release.version }}
        {% else -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                {{ self::remote_url() }}/releases/tag/{{ release.version }}
        {% endif -%}
    {% else -%}
        {% if release.previous.version -%}
            [Unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...HEAD
        {% endif -%}
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false

commit_preprocessors = [
    { pattern = '\(#([0-9]+)\)', replace = "([#${1}](https://github.com/julienandreu/switchboard/issues/${1}))" },
]

commit_parsers = [
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^doc", group = "Documentation" },
    { message = "^test", group = "Testing" },
    { message = "^style", group = "Styling" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore", group = "Miscellaneous" },
    { body = ".*security", group = "Security" },
    { message = "^revert", group = "Reverted" },
]

filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
protect_breaking_commits = true

[remote.github]
owner = "julienandreu"
repo = "switchboard"

[bump]
features_always_bump_minor = false
breaking_always_bump_major = false
initial_tag = "0.1.0"
